namespace Lvl3Mage.EditorDevToolkit.Runtime
{
	public static class EditorStyleTypes
	{
		public const string
			ColorPickerBox = "ColorPickerBox",
			In_BigTitle = "In BigTitle",
			miniLabel = "miniLabel",
			LargeLabel = "LargeLabel",
			BoldLabel = "BoldLabel",
			MiniBoldLabel = "MiniBoldLabel",
			WordWrappedLabel = "WordWrappedLabel",
			WordWrappedMiniLabel = "WordWrappedMiniLabel",
			WhiteLabel = "WhiteLabel",
			WhiteMiniLabel = "WhiteMiniLabel",
			WhiteLargeLabel = "WhiteLargeLabel",
			WhiteBoldLabel = "WhiteBoldLabel",
			MiniTextField = "MiniTextField",
			Radio = "Radio",
			miniButton = "miniButton",
			miniButtonLeft = "miniButtonLeft",
			miniButtonMid = "miniButtonMid",
			miniButtonRight = "miniButtonRight",
			toolbar = "toolbar",
			toolbarbutton = "toolbarbutton",
			toolbarPopup = "toolbarPopup",
			toolbarDropDown = "toolbarDropDown",
			toolbarTextField = "toolbarTextField",
			ToolbarSeachTextField = "ToolbarSeachTextField",
			ToolbarSeachTextFieldPopup = "ToolbarSeachTextFieldPopup",
			ToolbarSeachCancelButton = "ToolbarSeachCancelButton",
			ToolbarSeachCancelButtonEmpty = "ToolbarSeachCancelButtonEmpty",
			SearchTextField = "SearchTextField",
			SearchCancelButton = "SearchCancelButton",
			SearchCancelButtonEmpty = "SearchCancelButtonEmpty",
			HelpBox = "HelpBox",
			AssetLabel = "AssetLabel",
			AssetLabel_Partial = "AssetLabel Partial",
			AssetLabel_Icon = "AssetLabel Icon",
			selectionRect = "selectionRect",
			MinMaxHorizontalSliderThumb = "MinMaxHorizontalSliderThumb",
			DropDownButton = "DropDownButton",
			Label = "Label",
			MiniLabel = "MiniLabel",
			ProgressBarBack = "ProgressBarBack",
			ProgressBarBar = "ProgressBarBar",
			ProgressBarText = "ProgressBarText",
			FoldoutPreDrop = "FoldoutPreDrop",
			IN_Title = "IN Title",
			IN_TitleText = "IN TitleText",
			BoldToggle = "BoldToggle",
			Tooltip = "Tooltip",
			NotificationText = "NotificationText",
			NotificationBackground = "NotificationBackground",
			MiniPopup = "MiniPopup",
			textField = "textField",
			ControlLabel = "ControlLabel",
			ObjectField = "ObjectField",
			ObjectFieldThumb = "ObjectFieldThumb",
			ObjectFieldMiniThumb = "ObjectFieldMiniThumb",
			Toggle = "Toggle",
			ToggleMixed = "ToggleMixed",
			ColorField = "ColorField",
			Foldout = "Foldout",
			TextFieldDropDown = "TextFieldDropDown",
			TextFieldDropDownText = "TextFieldDropDownText";
	}
}